name: sdk_flutter
description: "Taly Payment Gateway SDK for Flutter"
version: 0.0.1
homepage: https://www.taly.io/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.7.0
  plugin_platform_interface: ^2.0.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^8.0.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/icons/
    - assets/images/

  uses-material-design: true

  plugin:
    platforms:
      android:
        package: io.taly.sdk_flutter
        pluginClass: SdkFlutterPlugin
      ios:
        pluginClass: SdkFlutterPlugin